// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBV5hTVfreZOfFCk-nMHu435MpygXEVNg',
    appId: '1:812237372412:web:2d31204c0ff942c7129079',
    messagingSenderId: '812237372412',
    projectId: 'inicio-sesion-2022-668b4',
    authDomain: 'inicio-sesion-2022-668b4.firebaseapp.com',
    storageBucket: 'inicio-sesion-2022-668b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1P0ir73fZKBI7-CJ_c5lyqiaLR2qh6V8',
    appId: '1:812237372412:android:ffaddd84ceae9bd2129079',
    messagingSenderId: '812237372412',
    projectId: 'inicio-sesion-2022-668b4',
    storageBucket: 'inicio-sesion-2022-668b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNvJahDuM3tdmZLHmPvMuZ5NLzjiQbNLg',
    appId: '1:812237372412:ios:86be8646e03b33b5129079',
    messagingSenderId: '812237372412',
    projectId: 'inicio-sesion-2022-668b4',
    storageBucket: 'inicio-sesion-2022-668b4.appspot.com',
    iosClientId: '812237372412-ah90o4aba1o001qjhuosk5pj9iqutnp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );
}
